### ISSUE TITLE
User directory path issue?

### ISSUE THREAD

**Issue by alarum** [timbotron/taskshare#2]
Warning: require(vendor/bcosca/fatfree/lib/base.php) [function.require]: failed to open stream: No such file or directory in /path/to/taskshare/index.php

Obviously vendor/bcosca/fatfree/lib/base.php doesn't exist on my server, I can just change this path to the F3 installation then?

**Comment by timbotron** [comment]
It's designed to utilize composer to install F3 from packagist, which would install it in the vendor/bcosca.. directory.

I think if you change that to point to your F3's installations base.php it should be fine, but haven't tested.

If you haven't checked out composer, you should check it out! Super helpful in keeping your projects up to date with latest code from various libraries you're utilizing.

**Comment by timbotron** [comment]
Also I think you are the first person to install this besides me. Let me know if you run into any more issues; happy to help!
