### ISSUE TITLE
This App does not run!!!!

### ISSUE THREAD

**Issue by asrarahmadehsan** [timbotron/taskshare#3]
I am using XAMPP, and I when run, I get the following error.

Warning: require(vendor/bcosca/fatfree/lib/base.php): failed to open stream: No such file or directory in C:\xampp\htdocs\taskshare\index.php on line 3

Fatal error: require(): Failed opening required 'vendor/bcosca/fatfree/lib/base.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\taskshare\index.php on line 3

**Comment by timbotron** [comment]
@asrarahmadehsan hi! First off, thanks for trying out Taskshare.

Taskshare relies on composer, which is a php package manager. I am not 100% certain that XAMPP will give you shell access to your virtual server so you can run the composer commands..

But basically, you need to get the project root directory, and run: `php composer.phar install` and it will download the necessary f3 package that taskshare relies on.

For more information: https://getcomposer.org/doc/00-intro.md

I am planning on revamping Taskshare soon with some enhancements, and, you know, some actual documentation. :/

**Comment by timbotron** [comment]
I'm going to assume based on your next issue you opened that you did get it to run.
